//------------------------------------------------------------------------------
// <auto-generated>
// This code is generated by the program.
// Executable version: 4.0.30319.42000
//
// Changes to this file may cause incorrect operation and will be lost if
// re-generate code.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcheAgeLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
